open-ce/pytorch-feedstock

recipe/build.sh
recipe/meta.yaml

Fixes https://github.com/open-ce/pytorch-feedstock/issues/12.

Fix x86 build

---

recipe/build.sh
recipe/meta.yaml

Fixes build failure on baremetal.

Fixed build on baremetal

---

recipe/build.sh
tests/open-ce-tests.yaml

Add initial PyTorch tests

---

recipe/meta.yaml

Allows PyTorch 1.7 to work with Python 3.7.

Add typing_extensions for Python 3.7

---

recipe/build.sh
recipe/meta.yaml

Fixes https://github.com/open-ce/open-ce/issues/177.

Fix to not build using Ninja as CMAKE GENERATOR

---

recipe/build.sh
recipe/meta.yaml

use v1.6.0 for onnx submodule

---

recipe/0304-PR47800-skip-tests-without-fbgemm-support.patch
recipe/meta.yaml
tests/open-ce-tests.yaml

Fixes https://github.com/open-ce/pytorch-feedstock/issues/21.

fix pytorch tests

---

tests/open-ce-tests.yaml

This PR requires open-ce/open-ce#234

Use the FEEDSTOCK_DIR environment variable

---

tests/open-ce-tests.yaml

Added to resolve the following test failure:
```
Failed test: Run PyTorch test_jit_fuser_te
Running test_jit_fuser_te ... [2020-12-28 14:27:15.606876]
Executing ['/opt/conda/envs/opence-conda-env-20201228141615/bin/python', 'test_jit_fuser_te.py'] ... [2020-12-28 14:27:15.606927]
Traceback (most recent call last):
File "test_jit_fuser_te.py", line 28, in <module>
from test_jit import backward_graph, all_backward_graphs, get_lstm_inputs, get_milstm_inputs, \
File "/home/builder/refresh_16Dec/pytorch/test/test_jit.py", line 8, in <module>
from jit.test_recursive_script import TestRecursiveScript  # noqa: F401
File "/home/builder/refresh_16Dec/pytorch/test/jit/test_recursive_script.py", line 5, in <module>
import typing_extensions
ModuleNotFoundError: No module named 'typing_extensions' …
```

install typing_extensions

---

recipe/meta.yaml

Added `git` as build time dependency.

Added git as a build dependency

---

tests/open-ce-tests.yaml

Tests are seen to fail at setup stage on M4-2 with the error -` git: command not found`

install git for tests

---

recipe/0105-workaround-for-compile-issue-with-glibc-memcpy-GLIBC.patch
recipe/meta.yaml

Fixes https://github.com/open-ce/open-ce/issues/236.

workaround for compile issue with glibc memcpy GLIBC

---

tests/open-ce-tests.yaml

Fixes https://github.com/open-ce/pytorch-feedstock/issues/30.

install gxx for jit_fuser tests

---

recipe/build.sh
scripts/pytorch-activate-env-vars.sh
scripts/pytorch-deactivate-env-vars.sh

Fixes https://github.com/open-ce/open-ce/issues/258.

Ensure scripts have Apache-2 licensing

---

recipe/meta.yaml
recipe/open-ce-info.yaml

Add third party information that can be read by the open-ce get licenses tool. See open-ce/open-ce#335.

Add open-ce info file

---

recipe/build.sh
recipe/meta.yaml

Fixes https://github.com/open-ce/pytorch-feedstock/issues/38.

disable build with mpi

---

recipe/meta.yaml

Fixes https://github.com/open-ce/pytorch-feedstock/issues/46.

remove dependency on scikit-image

---

recipe/meta.yaml
tests/open-ce-tests.yaml

Fixes https://github.com/open-ce/pytorch-feedstock/issues/45.

update to remove dependencies that are needed by tests

---

tests/open-ce-tests.yaml

Fixes https://github.com/open-ce/pytorch-feedstock/issues/49.

pin numba in tests

---

meta_recipe/meta.yaml
recipe/build.sh
recipe/meta.yaml

If this is a cpu build and 'cudatoolkit'

fix cpu build

---

recipe/build.sh
recipe/meta.yaml

Fixes https://github.com/open-ce/pytorch-feedstock/issues/54.

reorganize build script code

---

recipe/meta.yaml
recipe/open-ce-info.yaml

update license information

---

recipe/build.sh
recipe/meta.yaml

Disable TensorRT in OpenCE1.3 as it doesn't fit dependency-wise.
Will re-enable in 1.4 with TRT8.
Also - update the submodule git hash for ONNX to one that matches 1.7.

[1.3] Disable TensorRT

---

recipe/0306-skip-test_clamp.patch
recipe/0308-skip-test_qtopk.patch
tests/open-ce-tests.yaml

- Pull change from - https://github.com/open-ce/pytorch-feedstock/pull/50 to fix numba integration test failures. 
- Re-add change to skip `test_clamp` as it still fails. 
- Add change to skip `test_qtopk` as it fails. 

fix feedstock tests 

---

recipe/meta.yaml

fix build for cuda 11.2

---

recipe/build.sh
recipe/meta.yaml

[r1.7.1] use TBB for CPU and OpenMP for CUDA

---

meta_recipe/meta.yaml

Use torchtext-base in PyTorch meta-package. This is required because we now have two variants for torchtext - https://github.com/open-ce/torchtext-feedstock/pull/28

use torchtext-base in the meta_recipe

---

meta_recipe/meta.yaml
recipe/meta.yaml
tests/open-ce-tests.yaml

- Refresh to v1.10.1- https://github.com/open-ce/open-ce/issues/570
- Remove py36 specific code. 

refresh to v1.10.1

---

meta_recipe/meta.yaml
recipe/meta.yaml
tests/open-ce-tests.yaml

[main] refresh to v1.10.1 (#74)

---

recipe/meta.yaml

Pin zlib used to avoid the following error seen during build:
`/lib/libz.so.1: undefined reference to memcpy@GLIBC_2.14`

[1.2] pin zlib to fix build

---

meta_recipe/meta.yaml
recipe/meta.yaml

- Refresh to v1.10.2
- Remove pillow pin
- Add test block
https://github.com/open-ce/open-ce/issues/584

[1.5] refresh to v1.10.2

---

recipe/0108-change-mcpu-and-mtune.patch
recipe/build.sh
recipe/meta.yaml

port changes from 1.5 branch

---

meta_recipe/meta.yaml

fix version in meta package

---

recipe/meta.yaml

This PR pins `zlib` to avoid failure due to use of new `zlib `released by Anaconda a day back. 

pin zlib to fix build failure

---

recipe/meta.yaml

use snappy v1.1.8 to avoid build failure

[1.2] use snappy v1.1.8 to avoid build failure

---

recipe/meta.yaml

removed PKG_HASH from build string

---

recipe/0314-fix-nullpointer-error.patch
recipe/build.sh
recipe/meta.yaml

[main] port changes from 1.6 branch

---

recipe/build.sh
recipe/meta.yaml

[1.5] fix build failure for P10

---

pytorch-1.12/recipe/build.sh
pytorch-1.12/recipe/meta.yaml

Add change to use system GCC for P10. 

use system GCC for P10

---

pytorch-1.12/meta_recipe/meta.yaml
pytorch-1.12/recipe/meta.yaml
tests/open-ce-tests.yaml

refresh to 1.12.1

---

pytorch-1.13/meta_recipe/meta.yaml
pytorch-1.13/recipe/0108-skip-half-test.patch
pytorch-1.13/recipe/meta.yaml
tests/open-ce-tests.yaml

update to version 1.13.1

---

pytorch-1.12/recipe/0303-PR89925-security-fix.patch
pytorch-1.12/recipe/meta.yaml

apply security patch from PR 89925

---

pytorch-2.0/recipe/0309-fallback-to-cpu_kernel-with-VSX.patch
pytorch-2.0/recipe/meta.yaml
tests/open-ce-tests.yaml

fix for power

---

pytorch-2.0/recipe/0310-PR100149.patch
pytorch-2.0/recipe/meta.yaml

add patch to remove vsx suffix in sleef calls for P10

---

pytorch-2.0/meta_recipe/meta.yaml
pytorch-2.0/recipe/meta.yaml

refresh to v2.0.1

---

tests/open-ce-tests.yaml

[1.7] fix tests

---

pytorch-2.0/recipe/0311-PR104956.patch
pytorch-2.0/recipe/meta.yaml

use patch from PR104956

---

pytorch-2.0/recipe/build.sh
pytorch-2.0/recipe/meta.yaml

set mcpu and mtune options for p10

---

pytorch-1.10/recipe/0100-set-cmake_minimum_required-to-3.14-cuda11.2.patch
pytorch-1.10/recipe/meta.yaml

fix pytorch build failure for cuda11.2

---

pytorch-2.0/recipe/build.sh
pytorch-2.0/recipe/meta.yaml

attempt to fix env creation

---

pytorch-1.10/recipe/build.sh
pytorch-1.10/recipe/meta.yaml
pytorch-2.0/recipe/0311-Disabled-Wno-error-flag-for-p10.patch
pytorch-2.0/recipe/build.sh
pytorch-2.0/recipe/meta.yaml

Fix for P10 using gcc-toolset-12

---

tests/open-ce-tests.yaml

Fixed test failure for test_dataloader

---

tests/open-ce-tests.yaml

Skipped test_multiprocessing_iterdatapipe test

---

tests/open-ce-tests.yaml

Added -y flag to conda command

---

pytorch-2.1.2/recipe/build.sh
pytorch-2.1.2/recipe/meta.yaml

Changes for gcc-toolset-12

---

pytorch-2.1.2/recipe/0312-Disabled-Wno-error-flag-for-p10.patch
pytorch-2.1.2/recipe/meta.yaml

Disabled Wno-error-flag for p10

---

pytorch-2.1.2/recipe/build.sh
pytorch-2.1.2/recipe/meta.yaml

use libnvjitlink package for libnvjitlink.so

use libnvjitlink package for libnvjitlink.so

---

pytorch-2.1.2/recipe/meta.yaml

add filter for libnvjitlink

---

pytorch-2.1.2/recipe/meta.yaml

pin to use appropriate cuda version

---

pytorch-2.0/recipe/0312-Fix-for-CVE-2024-31583-and-CVE-2024-31580.patch
pytorch-2.0/recipe/meta.yaml

Backport fix for CVE-2024-31583 and CVE-2024-31580

---

pytorch-2.1.2/recipe/0313-Fix-for-CVE-2024-31583-and-CVE-2024-31580.patch
pytorch-2.1.2/recipe/meta.yaml

Fix CVE-2024-31583-and-CVE-2024-3158
Remove networkx pin

Fix CVE-2024-31583-and-CVE-2024-31580

---

pytorch-2.1.2/recipe/meta.yaml

zlib CVE-2023-45853 fix
